#!/bin/sh
. /etc/rc.subr

#configure below
name=servicename
desc="Service description"
command="/full/commandpath"
user=runasuser

#don't change anything past this point

rcvar="${name}_enable"
pidfile=/var/run/${name}.pid

start_cmd="service_start"
stop_cmd="service_stop"
status_cmd="service_status"

service_start() {
        echo Starting ${name}
        /usr/sbin/daemon -u ${user} -p ${pidfile} ${command}
}

service_status() {
        if [ -e ${pidfile} ]; then
                srvcpid=`cat ${pidfile}`;
                echo ${name} is running as pid ${srvcpid}
        else
                echo ${name} is not running.
        fi
}

service_stop() {
        if [ -e ${pidfile} ]; then
                echo Stopping ${name} ...
                kill `cat ${pidfile}`;
        else
                echo ${name} is not running.
        fi
}

load_rc_config $name
run_rc_command "$1"
