#!/bin/sh
. /etc/rc.subr

#configure below

name=servicename
desc="Service description"
command="/full/commandpath"
user=runasuser

#don't change anything past this point unless you know what you're doing

rcvar="${name}_enable"
pidfile=/var/run/${name}.pid

start_cmd="service_start"
stop_cmd="service_stop"
status_cmd="service_status"
#restart_cmd="service_restart"

service_start() {
        if [ -e ${pidfile} ]; then
                echo ${name} is already running.
        else
                echo Starting ${name}
                /usr/sbin/daemon -u ${user} -p ${pidfile} ${command} > /dev/null 2>&1
        fi
}

service_status() {
                srvcpid=0
        if [ -e ${pidfile} ]; then
                srvcpid=`cat ${pidfile}`;
                echo ${name} is running as pid ${srvcpid}
        else
                echo ${name} is not running.
        fi
}

service_stop() {
        if [ -e ${pidfile} ]; then
                echo -n Stopping ${name} 
                kill `cat ${pidfile}`;
                while [ -e ${pidfile} ]
                do
                        echo -n "."
                        sleep 1
                done
                echo "  Done."
        else
                echo ${name} is not running.
        fi
}

service_restart() {
        if [ -e ${pidfile} ]; then
                service_stop
                service_start
        else
                echo ${name} is not running.
        fi
}

load_rc_config $name
run_rc_command "$1"
